#!#!/bin/sh
echo "127.0.0.1 mb3admin.com www.mb3admin.com" >> /etc/hosts
cd /var/packages/EmbyServer/target/mono/bin
curl https://raw.githubusercontent.com/kingsnakerrr/embykey/master/mb3admin.com.cert.pem >> /etc/ssl/certs/ca-certificates.crt
./cert-sync /etc/ssl/certs/ca-certificates.crt
cd /usr/local/etc/nginx/conf.d/*-*-*-*
wget https://raw.githubusercontent.com/kingsnakerrr/embykey/master/user.conf
nginx -s reload